default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pick_me_development

test:
  <<: *default
  database: pick_me_test

production:
  <<: *default
  database: pick_me_production
  username: testing
  password: <%= ENV["PICK_ME_DATABASE_PASSWORD"] %>
